"""Standalone multi-session Azure Elastic SAN connect script for FreeBSD 13+.

This is a separate implementation from the Linux connect script in
"CLI (Linux) Multi-Session Connect Scripts". FreeBSD uses a different iSCSI
initiator stack (iscsid/iscsictl/iscsi.conf, sysrc/service) than Linux
(open-iscsi/iscsiadm, distro package managers), so the two scripts are kept
independent rather than sharing a code path.

Prerequisites (see README.md in this directory for full detail):
    * FreeBSD 13 or later with the native iSCSI initiator
      (iscsi(4)/iscsid(8)/iscsictl(8)) available -- /dev/iscsi must exist.
    * Python 3.
    * Azure CLI ('az') with the 'elastic-san' extension. On FreeBSD, Azure
      CLI is provided by the FreeBSD Ports Collection / community packages
      (e.g. sysutils/py-azure-cli) and is NOT part of Microsoft's
      first-class supported install matrix
      (https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux).
      This script verifies the 'elastic-san' extension is present but cannot
      verify upstream compatibility beyond that -- validate it yourself.
    * Root privileges for any mutating action (writing /etc/iscsi.conf,
      enabling/starting iscsid, adding iSCSI sessions). --dry-run does not
      require root and performs no mutation.

This script intentionally does NOT:
    * call iscsiadm, systemd, or any Linux package manager;
    * call 'iscsictl -R -a' or otherwise remove/tear down sessions;
    * restart the iscsid service or touch sessions it did not create;
    * assemble gmultipath devices (session creation is not multipath device
      assembly -- see README.md).
"""

import argparse
import json
import os
import re
import shutil
import socket
import subprocess
import sys
import tempfile
import threading

try:
    from urllib.request import ProxyHandler, Request, build_opener
    from urllib.error import HTTPError, URLError
except ImportError:  # pragma: no cover - py2 fallback retained for parity with the Linux script
    from urllib2 import HTTPError, ProxyHandler, Request, URLError, build_opener

try:
    string_types = (basestring,)  # noqa: F821 - py2 fallback
except NameError:
    string_types = (str,)


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

IMDS_COMPUTE_URL = "http://169.254.169.254/metadata/instance/compute?api-version=2021-02-01"
IMDS_TIMEOUT_SECONDS = 5
AZ_CLI_TIMEOUT_SECONDS = 30
SHORT_COMMAND_TIMEOUT_SECONDS = 15
# iscsictl -A blocks (with -w) until the session is established or the wait
# expires; bound the *subprocess* wait comfortably above the -w value so the
# external timeout only fires if iscsictl itself hangs, not on ordinary
# session-establishment latency.
ISCSICTL_SESSION_WAIT_SECONDS = 30
ISCSICTL_COMMAND_TIMEOUT_SECONDS = ISCSICTL_SESSION_WAIT_SECONDS + 15

MAX_IQN_UTF8_BYTES = 223
PHYSICAL_ZONE_PATTERN = re.compile(r"^[a-z0-9.-]+$")
SUBSCRIPTION_ID_PATTERN = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
)

DEFAULT_ISCSI_CONF_PATH = "/etc/iscsi.conf"
ISCSI_DEVICE_NODE = "/dev/iscsi"
REQUIRED_FREEBSD_TOOLS = ("iscsictl", "service", "sysrc")

# These markers are intentionally origin-neutral (no "generated by <this script>" text): both
# this standalone script and the Azure portal's generated FreeBSD connect script write to the
# same /etc/iscsi.conf and must recognize/replace each other's managed block rather than treating
# it as a stray, hand-edited marker. Keep this pair byte-for-byte identical to MANAGED_BLOCK_BEGIN
# / MANAGED_BLOCK_END in VolumeHelpers.ts's generateFreeBsdConnectScript.
MANAGED_BLOCK_BEGIN = "# BEGIN AZURE ELASTIC SAN FREEBSD MANAGED BLOCK -- DO NOT EDIT"
MANAGED_BLOCK_END = "# END AZURE ELASTIC SAN FREEBSD MANAGED BLOCK"

# Characters that would break the iscsi.conf(5) grammar or allow one
# configured value to inject a second statement/stanza.
_FORBIDDEN_CONFIG_CHARS = frozenset('"{}#;')
NICKNAME_PATTERN = re.compile(r"^[a-z0-9][a-z0-9_-]{0,127}$")


class ElasticSanConnectError(Exception):
    """Raised for any expected, actionable failure in this script."""


# ---------------------------------------------------------------------------
# Bounded subprocess execution (shared by Azure CLI and FreeBSD tool calls)
# ---------------------------------------------------------------------------

def _decode_output(value):
    return value.decode("utf-8") if isinstance(value, bytes) else value


def _run_subprocess(command, description, timeout):
    """Run *command* (an argv list; never a shell string) with a hard wall-clock
    timeout, returning (returncode, stdout, stderr). Never raises on a non-zero
    exit code -- callers decide whether that is fatal."""
    try:
        process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    except OSError as error:
        raise ElasticSanConnectError("{} failed to start: {}".format(description, error))

    result = []
    communication_errors = []

    def communicate():
        try:
            result.append(process.communicate())
        except (OSError, ValueError) as error:
            communication_errors.append(error)

    communication_thread = threading.Thread(target=communicate)
    communication_thread.daemon = True
    communication_thread.start()
    communication_thread.join(timeout)
    if communication_thread.is_alive():
        process.kill()
        communication_thread.join()
        raise ElasticSanConnectError(
            "{} timed out after {} seconds".format(description, timeout)
        )
    if communication_errors:
        raise ElasticSanConnectError(
            "{} failed while collecting output: {}".format(
                description, communication_errors[0]
            )
        )

    out, err = result[0]
    return process.returncode, _decode_output(out), _decode_output(err).strip()


def _run_command(command, description, timeout=AZ_CLI_TIMEOUT_SECONDS):
    """Run *command* and raise ElasticSanConnectError if it exits non-zero."""
    returncode, out, err = _run_subprocess(command, description, timeout)
    if returncode != 0:
        detail = err if err else "exit code {}".format(returncode)
        raise ElasticSanConnectError("{} failed: {}".format(description, detail))
    return out


def _run_az_command(command, description):
    return _run_command(command, description, AZ_CLI_TIMEOUT_SECONDS)


# ---------------------------------------------------------------------------
# Preflight checks
# ---------------------------------------------------------------------------

def check_az_cli_available():
    """Confirm 'az' is on PATH and the 'elastic-san' extension is installed.

    Azure CLI on FreeBSD is provided by the FreeBSD Ports Collection /
    community packages (e.g. sysutils/py-azure-cli); it is not part of
    Microsoft's first-class supported install matrix. This function verifies
    the elastic-san extension is present, which is the most that can be
    checked programmatically -- broader compatibility must still be
    validated by the operator.
    """
    if shutil.which("az") is None:
        raise ElasticSanConnectError(
            "Azure CLI ('az') was not found on PATH. On FreeBSD, Azure CLI is provided by the "
            "FreeBSD Ports Collection / community packages (e.g. sysutils/py-azure-cli) and is "
            "not part of Microsoft's first-class supported install matrix "
            "(https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux). Install it "
            "and 'az login', then re-run."
        )
    extension_names = _run_az_command(
        ["az", "extension", "list", "--query", "[].name", "--output", "tsv"],
        "Azure CLI extension inventory",
    )
    installed = {name.strip() for name in extension_names.splitlines() if name.strip()}
    if "elastic-san" not in installed:
        raise ElasticSanConnectError(
            "The Azure CLI 'elastic-san' extension is not installed. Because Azure CLI on "
            "FreeBSD is community-provided and not on Microsoft's first-class install matrix, "
            "extension compatibility is not verified upstream and must be checked manually. "
            "Run 'az extension add -n elastic-san', confirm 'az elastic-san volume show --help' "
            "works, and re-run this script."
        )


def check_freebsd_mutation_prerequisites():
    """Preflight required before any mutating action. Not run for --dry-run."""
    if os.geteuid() != 0:
        raise ElasticSanConnectError(
            "This action modifies {} and iSCSI session state, and must be run as root "
            "(re-run under su/doas or another privileged shell). Use --dry-run to preview a "
            "plan without root.".format(DEFAULT_ISCSI_CONF_PATH)
        )
    missing_tools = [tool for tool in REQUIRED_FREEBSD_TOOLS if shutil.which(tool) is None]
    if missing_tools:
        raise ElasticSanConnectError(
            "Required FreeBSD tool(s) not found on PATH: {}. This script targets FreeBSD 13+ "
            "native iSCSI tooling (iscsictl/service/sysrc) only; it does not use iscsiadm, "
            "systemd, or Linux package managers.".format(", ".join(missing_tools))
        )
    if not os.path.exists(ISCSI_DEVICE_NODE):
        raise ElasticSanConnectError(
            "{} was not found, so the FreeBSD iSCSI initiator kernel driver does not appear to "
            "be loaded. Use a GENERIC (or equivalent) kernel with the iscsi_initiator driver, "
            "or load it explicitly ('kldload iscsi', or iscsi_load=\"YES\" in "
            "/boot/loader.conf) before retrying.".format(ISCSI_DEVICE_NODE)
        )


# ---------------------------------------------------------------------------
# IMDS / zonal-affinity helpers
#
# Semantics below (IMDS endpoint/header/no-proxy/timeout, bounded Azure CLI,
# canonical SAN subscription resolution, same-subscription/same-region
# checks, explicit-subscription ARM Locations lookup, mapping validation,
# and the provisional ":az-<physicalZone>" IQN suffix) intentionally mirror
# "CLI (Linux) Multi-Session Connect Scripts/connect_for_documentation.py"
# so operators see identical zonal-affinity behavior on both platforms.
# ---------------------------------------------------------------------------

def get_vm_compute_metadata():
    request = Request(IMDS_COMPUTE_URL, headers={"Metadata": "true"})
    opener = build_opener(ProxyHandler({}))
    try:
        response = opener.open(request, timeout=IMDS_TIMEOUT_SECONDS)
        try:
            payload = _decode_output(response.read())
        finally:
            response.close()
    except HTTPError as error:
        raise ElasticSanConnectError("IMDS request failed with HTTP status {}".format(error.code))
    except URLError as error:
        raise ElasticSanConnectError("IMDS request failed: {}".format(error.reason))
    except socket.timeout:
        raise ElasticSanConnectError(
            "IMDS request timed out after {} seconds".format(IMDS_TIMEOUT_SECONDS)
        )

    try:
        compute = json.loads(payload)
    except ValueError as error:
        raise ElasticSanConnectError("IMDS returned invalid JSON: {}".format(error))
    if not isinstance(compute, dict):
        raise ElasticSanConnectError("IMDS compute metadata must be a JSON object")
    return compute


def _required_metadata_value(compute, field_name):
    value = compute.get(field_name)
    if not isinstance(value, string_types) or not value.strip():
        raise ElasticSanConnectError(
            "IMDS compute metadata is missing a valid '{}' value".format(field_name)
        )
    return value.strip()


def canonicalize_subscription_id(subscription_id, source):
    if not isinstance(subscription_id, string_types):
        raise ElasticSanConnectError("{} subscription ID must be a GUID".format(source))
    canonical_subscription_id = subscription_id.strip().lower()
    if SUBSCRIPTION_ID_PATTERN.match(canonical_subscription_id) is None:
        raise ElasticSanConnectError("{} subscription ID must be a GUID".format(source))
    return canonical_subscription_id


def resolve_elastic_san_subscription_id(elastic_san_subscription):
    command = ["az", "account", "show"]
    if elastic_san_subscription is not None:
        command.extend(["--subscription", elastic_san_subscription])
    command.extend(["--query", "id", "--output", "tsv"])
    subscription_id = _run_az_command(
        command, "Elastic SAN subscription resolution"
    ).strip()
    if not subscription_id:
        raise ElasticSanConnectError("Elastic SAN subscription resolution returned an empty ID")
    return canonicalize_subscription_id(subscription_id, "Elastic SAN")


def get_elastic_san_location(elastic_san_subscription_id, resource_group_name, elastic_san_name):
    command = [
        "az",
        "elastic-san",
        "show",
        "-g",
        resource_group_name,
        "--elastic-san-name",
        elastic_san_name,
        "--subscription",
        elastic_san_subscription_id,
        "--query",
        "location",
        "--output",
        "tsv",
    ]
    location = _run_az_command(command, "Elastic SAN location lookup").strip()
    if not location:
        raise ElasticSanConnectError("Elastic SAN location lookup returned an empty location")
    return location


def get_azure_locations(elastic_san_subscription_id):
    elastic_san_subscription_id = canonicalize_subscription_id(
        elastic_san_subscription_id, "Elastic SAN"
    )
    url = (
        "https://management.azure.com/subscriptions/{}/locations"
        "?api-version=2022-12-01"
    ).format(elastic_san_subscription_id)
    command = ["az", "rest", "--method", "get", "--url", url]
    payload = _run_az_command(command, "Azure location REST query")
    try:
        response = json.loads(payload)
    except ValueError as error:
        raise ElasticSanConnectError(
            "Azure location REST query returned invalid JSON: {}".format(error)
        )
    if not isinstance(response, dict):
        raise ElasticSanConnectError("Azure location REST response must be a JSON object")
    locations = response.get("value")
    if not isinstance(locations, list):
        raise ElasticSanConnectError(
            "Azure location REST response must contain a top-level 'value' array"
        )
    return locations


def map_logical_to_physical_zone(locations, location_name, logical_zone):
    normalized_location = location_name.strip().lower()
    region = None
    for candidate in locations:
        if not isinstance(candidate, dict):
            raise ElasticSanConnectError("Azure location REST response contains a malformed region entry")
        candidate_name = candidate.get("name")
        if (
            isinstance(candidate_name, string_types)
            and candidate_name.strip().lower() == normalized_location
        ):
            region = candidate
            break

    if region is None:
        raise ElasticSanConnectError(
            "Azure location REST response has no region matching Elastic SAN location '{}'".format(
                location_name
            )
        )

    if "availabilityZoneMappings" not in region:
        raise ElasticSanConnectError(
            "Region '{}' is missing availabilityZoneMappings".format(region.get("name"))
        )

    mappings = region["availabilityZoneMappings"]
    if not isinstance(mappings, list) or not mappings:
        raise ElasticSanConnectError(
            "Region '{}' has malformed availabilityZoneMappings".format(region.get("name"))
        )

    normalized_logical_zone = logical_zone.strip()
    zone_map = {}
    for mapping in mappings:
        if not isinstance(mapping, dict):
            raise ElasticSanConnectError("availabilityZoneMappings contains a malformed entry")
        mapped_logical_zone = mapping.get("logicalZone")
        mapped_physical_zone = mapping.get("physicalZone")
        if (
            not isinstance(mapped_logical_zone, string_types)
            or not mapped_logical_zone.strip()
            or not isinstance(mapped_physical_zone, string_types)
            or not mapped_physical_zone.strip()
        ):
            raise ElasticSanConnectError("availabilityZoneMappings contains a malformed entry")
        mapped_logical_zone = mapped_logical_zone.strip()
        mapped_physical_zone = mapped_physical_zone.strip()
        if mapped_logical_zone in zone_map:
            raise ElasticSanConnectError(
                "availabilityZoneMappings contains duplicate logical zone '{}'".format(
                    mapped_logical_zone
                )
            )
        zone_map[mapped_logical_zone] = mapped_physical_zone

    if normalized_logical_zone not in zone_map:
        raise ElasticSanConnectError(
            "Region '{}' has no availability-zone mapping for logical zone '{}'".format(
                region.get("name"), logical_zone
            )
        )
    return zone_map[normalized_logical_zone]


def resolve_physical_zone(elastic_san_subscription, resource_group_name, elastic_san_name):
    compute = get_vm_compute_metadata()
    logical_zone = compute.get("zone")
    if not isinstance(logical_zone, string_types) or not logical_zone.strip():
        raise ElasticSanConnectError(
            "VM is not availability-zone pinned; IMDS compute.zone is empty or missing"
        )
    logical_zone = logical_zone.strip()
    imds_subscription_id = canonicalize_subscription_id(
        _required_metadata_value(compute, "subscriptionId"), "IMDS"
    )
    location_name = _required_metadata_value(compute, "location")

    elastic_san_subscription_id = resolve_elastic_san_subscription_id(elastic_san_subscription)
    if elastic_san_subscription_id != imds_subscription_id:
        raise ElasticSanConnectError(
            "Elastic SAN subscription '{}' does not match VM subscription '{}'".format(
                elastic_san_subscription_id, imds_subscription_id
            )
        )

    elastic_san_location = get_elastic_san_location(
        elastic_san_subscription_id, resource_group_name, elastic_san_name
    )
    if elastic_san_location.strip().lower() != location_name.strip().lower():
        raise ElasticSanConnectError("The VM and Elastic SAN must be in the same region.")

    locations = get_azure_locations(elastic_san_subscription_id)
    return map_logical_to_physical_zone(locations, elastic_san_location, logical_zone)


def decorate_target_iqn(target_iqn, physical_zone):
    normalized_physical_zone = physical_zone.strip().lower()
    if (
        not normalized_physical_zone
        or PHYSICAL_ZONE_PATTERN.match(normalized_physical_zone) is None
    ):
        raise ElasticSanConnectError(
            "Physical zone '{}' contains characters that are unsafe for an IQN suffix".format(
                physical_zone
            )
        )

    # Provisional contract: the Elastic SAN front end must parse and strip this
    # suffix before zonal-affinity routing can be used in production.
    decorated_iqn = "{}:az-{}".format(target_iqn, normalized_physical_zone)
    if len(decorated_iqn.encode("utf-8")) > MAX_IQN_UTF8_BYTES:
        raise ElasticSanConnectError(
            "Decorated target IQN exceeds the {}-byte UTF-8 limit".format(MAX_IQN_UTF8_BYTES)
        )
    return decorated_iqn


def get_volume_storage_target(
    elastic_san_subscription, resource_group_name, elastic_san_name, volume_group_name, volume_name
):
    """Look up a volume's iSCSI target (IQN, portal hostname, portal port)."""
    command = [
        "az",
        "elastic-san",
        "volume",
        "show",
        "-g",
        resource_group_name,
        "-e",
        elastic_san_name,
        "-v",
        volume_group_name,
        "-n",
        volume_name,
        "--query",
        "storageTarget",
        "--output",
        "json",
    ]
    if elastic_san_subscription is not None:
        command.extend(["--subscription", elastic_san_subscription])
    payload = _run_az_command(
        command, "Elastic SAN volume '{}' storage target lookup".format(volume_name)
    )
    try:
        storage_target = json.loads(payload)
    except ValueError as error:
        raise ElasticSanConnectError(
            "Elastic SAN volume '{}' storage target lookup returned invalid JSON: {}".format(
                volume_name, error
            )
        )
    if not isinstance(storage_target, dict):
        raise ElasticSanConnectError(
            "Elastic SAN volume '{}' storage target lookup must return a JSON object".format(
                volume_name
            )
        )
    try:
        target_iqn = storage_target["targetIqn"]
        target_portal_hostname = storage_target["targetPortalHostname"]
        target_portal_port = storage_target["targetPortalPort"]
    except KeyError as error:
        raise ElasticSanConnectError(
            "Elastic SAN volume '{}' storage target response is missing {}".format(
                volume_name, error
            )
        )
    return target_iqn, target_portal_hostname, target_portal_port


# ---------------------------------------------------------------------------
# iscsi.conf value/nickname validation
# ---------------------------------------------------------------------------

def validate_config_scalar(value, field_name):
    """Reject anything that could inject a new statement/stanza into
    iscsi.conf(5) (quotes, braces, comment/statement separators, or control
    characters including newlines) rather than attempting to escape it --
    the format has no documented escape sequence for these characters."""
    if not isinstance(value, string_types) or not value:
        raise ElasticSanConnectError("{} must be a non-empty string".format(field_name))
    if any(ord(character) < 0x20 for character in value):
        raise ElasticSanConnectError(
            "{} contains a control character, which is not permitted in an iscsi.conf "
            "value".format(field_name)
        )
    if any(character in _FORBIDDEN_CONFIG_CHARS for character in value):
        raise ElasticSanConnectError(
            "{} contains one of {} which is not permitted in an iscsi.conf value: {!r}".format(
                field_name, sorted(_FORBIDDEN_CONFIG_CHARS), value
            )
        )
    return value


def sanitize_identity_component(value, field_name):
    if not isinstance(value, string_types) or not value.strip():
        raise ElasticSanConnectError("{} must be a non-empty string".format(field_name))
    lowered = value.strip().lower()
    sanitized = re.sub(r"[^a-z0-9]+", "-", lowered).strip("-")
    if not sanitized:
        raise ElasticSanConnectError(
            "{} '{}' has no [a-z0-9] characters left to build a config nickname from".format(
                field_name, value
            )
        )
    return sanitized


def build_nickname(volume_group_name, volume_name, session_index):
    """Deterministic, collision-resistant iscsi.conf nickname for one
    (volume group, volume, session index) tuple. Same inputs always produce
    the same nickname, which is what makes managed-block regeneration
    idempotent across re-runs."""
    sanitized_group = sanitize_identity_component(volume_group_name, "Volume group name")
    sanitized_volume = sanitize_identity_component(volume_name, "Volume name")
    nickname = "esan-{}-{}-s{}".format(sanitized_group, sanitized_volume, session_index)
    if NICKNAME_PATTERN.match(nickname) is None:
        raise ElasticSanConnectError(
            "Generated nickname '{}' is not a safe iscsi.conf identifier (volume group/volume "
            "names may be too long or resolve to no usable characters)".format(nickname)
        )
    return nickname


class ManagedConfigEntry(object):
    __slots__ = ("nickname", "target_name", "target_address")

    def __init__(self, nickname, target_name, target_address):
        self.nickname = nickname
        self.target_name = target_name
        self.target_address = target_address


def render_managed_block(entries):
    """Render the full managed block (including BEGIN/END markers) for the
    given ManagedConfigEntry list. TargetName/TargetAddress are pre-validated
    by validate_config_scalar, so quoting them here cannot be broken out of."""
    lines = [MANAGED_BLOCK_BEGIN]
    for entry in entries:
        lines.append("{} {{".format(entry.nickname))
        lines.append('\tTargetName    = "{}"'.format(entry.target_name))
        lines.append('\tTargetAddress = "{}"'.format(entry.target_address))
        lines.append("\tHeaderDigest  = CRC32C")
        lines.append("\tDataDigest    = CRC32C")
        lines.append("\tEnable        = On")
        lines.append("}")
    lines.append(MANAGED_BLOCK_END)
    return ("\n".join(lines) + "\n").encode("utf-8")


# ---------------------------------------------------------------------------
# /etc/iscsi.conf atomic update with backup/rollback
# ---------------------------------------------------------------------------

def _split_managed_block(content_bytes):
    """Return (prefix, suffix) byte spans surrounding any existing managed
    block in *content_bytes*, preserving everything else byte-for-byte. If no
    managed block markers are present, the whole file is treated as prefix
    (the new block is appended). Raises if exactly one marker is present,
    which indicates hand-edited/corrupted state we should not try to guess
    our way through."""
    begin_bytes = MANAGED_BLOCK_BEGIN.encode("utf-8")
    end_bytes = MANAGED_BLOCK_END.encode("utf-8")
    begin_index = content_bytes.find(begin_bytes)
    end_index = content_bytes.find(end_bytes)

    if begin_index == -1 and end_index == -1:
        return content_bytes, b""

    if begin_index == -1 or end_index == -1:
        raise ElasticSanConnectError(
            "{} contains only one of the managed-block BEGIN/END markers. Refusing to modify "
            "it automatically; restore the file from a backup or remove the stray marker line "
            "by hand before retrying.".format(DEFAULT_ISCSI_CONF_PATH)
        )
    if end_index < begin_index:
        raise ElasticSanConnectError(
            "{} has a managed-block END marker before its BEGIN marker. Refusing to modify it "
            "automatically.".format(DEFAULT_ISCSI_CONF_PATH)
        )

    end_line_terminator = content_bytes.find(b"\n", end_index)
    end_of_end_line = end_line_terminator + 1 if end_line_terminator != -1 else len(content_bytes)
    prefix = content_bytes[:begin_index]
    suffix = content_bytes[end_of_end_line:]

    # Guard against a second, stray marker pair further down the file (e.g.
    # from a manually concatenated/restored backup). We already refuse to
    # guess our way through a single stray marker above; a duplicate pair
    # deserves the same treatment rather than being silently preserved in
    # 'suffix' forever.
    if begin_bytes in suffix or end_bytes in suffix:
        raise ElasticSanConnectError(
            "{} contains more than one managed-block marker pair. Refusing to modify it "
            "automatically; remove the duplicate BEGIN/END markers by hand before "
            "retrying.".format(DEFAULT_ISCSI_CONF_PATH)
        )

    return prefix, suffix


def compute_new_config_content(existing_content_bytes, managed_block_bytes):
    prefix, suffix = _split_managed_block(existing_content_bytes)
    if prefix and not prefix.endswith(b"\n"):
        prefix += b"\n"
    return prefix + managed_block_bytes + suffix


def read_config_file(path):
    """Return (content_bytes, existed, stat_result_or_None)."""
    if not os.path.exists(path):
        return b"", False, None
    with open(path, "rb") as handle:
        content = handle.read()
    return content, True, os.stat(path)


def backup_config(path, existing_content_bytes, existed):
    """Write a backup of the current config content before mutating it.
    Returns the backup path (or None if the file did not exist yet, in which
    case there is nothing to back up)."""
    if not existed:
        return None
    backup_path = "{}.bak.pre-esan-connect.{}".format(path, os.getpid())
    directory = os.path.dirname(path) or "."
    fd, temp_path = tempfile.mkstemp(prefix=".iscsi.conf.bak.", dir=directory)
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(existing_content_bytes)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temp_path, backup_path)
    except BaseException:
        if os.path.exists(temp_path):
            os.remove(temp_path)
        raise
    return backup_path


def write_config_atomically(path, new_content_bytes, original_stat):
    """Write *new_content_bytes* to *path* atomically via a temp file in the
    same directory + os.replace, preserving the original file's permissions
    and ownership where possible."""
    directory = os.path.dirname(path) or "."
    fd, temp_path = tempfile.mkstemp(prefix=".iscsi.conf.new.", dir=directory)
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(new_content_bytes)
            handle.flush()
            os.fsync(handle.fileno())
        if original_stat is not None:
            os.chmod(temp_path, original_stat.st_mode & 0o7777)
            # Ownership preservation only applies on platforms that expose
            # os.chown (i.e. POSIX/FreeBSD, the only supported target for
            # this script) -- "where possible" per the design requirements.
            if hasattr(os, "chown"):
                try:
                    os.chown(temp_path, original_stat.st_uid, original_stat.st_gid)
                except OSError as error:
                    raise ElasticSanConnectError(
                        "Failed to preserve ownership of {} on the replacement file: {}".format(
                            path, error
                        )
                    )
        else:
            os.chmod(temp_path, 0o644)
        os.replace(temp_path, path)
    except BaseException:
        if os.path.exists(temp_path):
            os.remove(temp_path)
        raise


def restore_config_from_backup(path, backup_path, existed, original_stat):
    """Roll back a mutation: restore the pre-mutation content and permissions
    (or remove the file entirely if it did not exist before this run created
    it). *original_stat* must be the stat() of the file captured before it
    was mutated -- the backup file itself is deliberately created with
    restrictive permissions regardless of the original file's mode, since
    unrelated stanzas preserved outside the managed block may contain CHAP
    secrets."""
    if not existed:
        if os.path.exists(path):
            os.remove(path)
        return
    with open(backup_path, "rb") as handle:
        backup_content = handle.read()
    write_config_atomically(path, backup_content, original_stat)


# ---------------------------------------------------------------------------
# iscsid service management
# ---------------------------------------------------------------------------

def ensure_iscsid_enabled_and_running():
    current = _run_command(
        ["sysrc", "-n", "iscsid_enable"], "sysrc iscsid_enable query", SHORT_COMMAND_TIMEOUT_SECONDS
    )
    if current.strip().upper() != "YES":
        _run_command(
            ["sysrc", "iscsid_enable=YES"], "sysrc iscsid_enable=YES", SHORT_COMMAND_TIMEOUT_SECONDS
        )
    returncode, _, _ = _run_subprocess(
        ["service", "iscsid", "onestatus"], "service iscsid onestatus", SHORT_COMMAND_TIMEOUT_SECONDS
    )
    if returncode != 0:
        _run_command(
            ["service", "iscsid", "start"], "service iscsid start", SHORT_COMMAND_TIMEOUT_SECONDS
        )


# ---------------------------------------------------------------------------
# iscsictl session inspection/management
# ---------------------------------------------------------------------------

def list_iscsi_sessions():
    """Parse 'iscsictl -L -v' into a list of per-session field dicts (keys
    such as 'Target name', 'Target portal', 'Session state'). The nickname
    used to add a session is not part of the kernel's session state and is
    therefore not recoverable from this listing -- sessions are correlated
    by (Target name, Target portal) only."""
    output = _run_command(
        ["iscsictl", "-L", "-v"], "iscsictl session listing", AZ_CLI_TIMEOUT_SECONDS
    )
    return _parse_iscsictl_verbose_sessions(output)


def _parse_iscsictl_verbose_sessions(output):
    sessions = []
    for block in output.split("\n\n"):
        if not block.strip():
            continue
        fields = {}
        for line in block.splitlines():
            if ":" not in line:
                continue
            label, _, value = line.partition(":")
            fields[label.strip()] = value.strip()
        if "Target name" in fields and "Target portal" in fields:
            sessions.append(fields)
    return sessions


def count_matching_sessions(sessions, target_name, target_address):
    return sum(
        1
        for session in sessions
        if session.get("Target name") == target_name
        and session.get("Target portal") == target_address
    )


def add_iscsi_session(nickname, config_path):
    command = [
        "iscsictl",
        "-A",
        "-n",
        nickname,
        "-c",
        config_path,
        "-w",
        str(ISCSICTL_SESSION_WAIT_SECONDS),
    ]
    _run_command(
        command, "iscsictl add session '{}'".format(nickname), ISCSICTL_COMMAND_TIMEOUT_SECONDS
    )


# ---------------------------------------------------------------------------
# Connection planning (shared by --dry-run and the real execution path)
# ---------------------------------------------------------------------------

class VolumeConnectionPlan(object):
    __slots__ = ("volume_name", "target_name", "target_address", "nicknames")

    def __init__(self, volume_name, target_name, target_address, nicknames):
        self.volume_name = volume_name
        self.target_name = target_name
        self.target_address = target_address
        self.nicknames = nicknames


def build_connection_plan(
    elastic_san_subscription,
    resource_group_name,
    elastic_san_name,
    volume_group_name,
    volume_names,
    number_of_sessions,
    enable_zonal_affinity=False,
):
    """Resolve targets and compute the deterministic nickname set for every
    volume. This performs only read-only discovery (IMDS, Azure CLI) and pure
    computation -- no filesystem or iscsictl calls -- so it is identical for
    --dry-run and the real execution path."""
    physical_zone = (
        resolve_physical_zone(elastic_san_subscription, resource_group_name, elastic_san_name)
        if enable_zonal_affinity
        else None
    )

    plans = []
    for volume_name in volume_names:
        target_iqn, target_hostname, target_port = get_volume_storage_target(
            elastic_san_subscription,
            resource_group_name,
            elastic_san_name,
            volume_group_name,
            volume_name,
        )
        if enable_zonal_affinity:
            target_iqn = decorate_target_iqn(target_iqn, physical_zone)

        target_name = validate_config_scalar(target_iqn, "Target IQN for '{}'".format(volume_name))
        target_address = validate_config_scalar(
            "{}:{}".format(target_hostname, target_port),
            "Target address for '{}'".format(volume_name),
        )
        nicknames = [
            build_nickname(volume_group_name, volume_name, session_index)
            for session_index in range(1, number_of_sessions + 1)
        ]
        plans.append(VolumeConnectionPlan(volume_name, target_name, target_address, nicknames))
    return plans


def render_full_managed_block(plans):
    entries = [
        ManagedConfigEntry(nickname, plan.target_name, plan.target_address)
        for plan in plans
        for nickname in plan.nicknames
    ]
    return render_managed_block(entries)


def describe_plan(plans, number_of_sessions):
    lines = []
    for plan in plans:
        lines.append(
            "{} -> target {} at {} ({} session(s), nicknames: {})".format(
                plan.volume_name,
                plan.target_name,
                plan.target_address,
                number_of_sessions,
                ", ".join(plan.nicknames),
            )
        )
    return lines


# ---------------------------------------------------------------------------
# Execution path (mutating)
# ---------------------------------------------------------------------------

def add_sessions_for_volume(plan, config_path, desired_sessions):
    existing_sessions = list_iscsi_sessions()
    existing_count = count_matching_sessions(existing_sessions, plan.target_name, plan.target_address)

    if existing_count > desired_sessions:
        raise ElasticSanConnectError(
            "{}: found {} existing session(s) to {} ({}), which exceeds the requested {} "
            "session(s). This script does not remove sessions -- reconcile the discrepancy "
            "manually (raise --num-of-sessions to match, or disconnect the extras yourself with "
            "'iscsictl -L -v' and 'iscsictl -R') and re-run.".format(
                plan.volume_name,
                existing_count,
                plan.target_name,
                plan.target_address,
                desired_sessions,
            )
        )

    if existing_count == desired_sessions:
        print(
            "{} [{}]: Skipped -- {} session(s) already established".format(
                plan.volume_name, plan.target_name, existing_count
            )
        )
        return

    for nickname in plan.nicknames[existing_count:]:
        add_iscsi_session(nickname, config_path)

    refreshed_sessions = list_iscsi_sessions()
    refreshed_count = count_matching_sessions(
        refreshed_sessions, plan.target_name, plan.target_address
    )
    if refreshed_count < desired_sessions:
        raise ElasticSanConnectError(
            "{}: expected {} session(s) to {} ({}) after connecting, but 'iscsictl -L -v' shows "
            "only {}. Investigate manually with 'iscsictl -L -v' before retrying.".format(
                plan.volume_name, desired_sessions, plan.target_name, plan.target_address, refreshed_count
            )
        )
    print(
        "{} [{}]: Connected with {} session(s)".format(
            plan.volume_name, plan.target_name, desired_sessions
        )
    )


def execute_connection_plan(plans, config_path, number_of_sessions):
    check_freebsd_mutation_prerequisites()
    ensure_iscsid_enabled_and_running()

    existing_content_bytes, existed, original_stat = read_config_file(config_path)
    backup_path = backup_config(config_path, existing_content_bytes, existed)

    new_managed_block = render_full_managed_block(plans)
    new_content = compute_new_config_content(existing_content_bytes, new_managed_block)
    write_config_atomically(config_path, new_content, original_stat)

    try:
        for plan in plans:
            add_sessions_for_volume(plan, config_path, number_of_sessions)
    except (ElasticSanConnectError, OSError) as error:
        restore_config_from_backup(config_path, backup_path, existed, original_stat)
        raise ElasticSanConnectError(
            "Failed while establishing iSCSI sessions; restored {} to its pre-run state. "
            "No previously-established sessions were removed. Original error: {}".format(
                config_path, error
            )
        )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def create_argument_parser():
    parser = argparse.ArgumentParser(
        description=(
            "Connect one or more Azure Elastic SAN volumes with multiple iSCSI sessions on "
            "FreeBSD 13+, using the native iscsid/iscsictl initiator."
        )
    )
    parser.add_argument(
        "--elastic-san-subscription",
        "--subscription",
        dest="elastic_san_subscription",
        help=(
            "Elastic SAN resource subscription name or ID. --subscription is retained as a "
            "compatibility alias."
        ),
    )
    parser.add_argument("-g", "--resource-group", dest="resource_group")
    parser.add_argument("-e", "--elastic-san", dest="elastic_san")
    parser.add_argument("-v", "--volume-group", dest="volume_group")
    parser.add_argument("-n", "--volumes", dest="volumes", nargs="+")
    parser.add_argument("-s", "--num-of-sessions", dest="num_of_sessions")
    parser.add_argument(
        "--enable-zonal-affinity",
        action="store_true",
        help=(
            "Opt in to provisional logical-to-physical availability-zone routing. Requires "
            "Elastic SAN front-end support for parsing the IQN suffix."
        ),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help=(
            "Perform all read-only discovery/mapping/config planning and print the plan, "
            "without running sysrc, service, or iscsictl, and without writing "
            + DEFAULT_ISCSI_CONF_PATH
            + ". Does not require root. Existing session counts are not inspected in this mode "
            "(inspecting them requires root); the plan assumes zero pre-existing sessions."
        ),
    )
    parser.add_argument(
        "--config-path",
        dest="config_path",
        default=DEFAULT_ISCSI_CONF_PATH,
        help=argparse.SUPPRESS,  # override for tests only; not part of the public CLI contract
    )
    return parser


def main(argv=None):
    parser = create_argument_parser()
    args = parser.parse_args(sys.argv[1:] if argv is None else argv)

    resource_group_name = args.resource_group
    elastic_san_name = args.elastic_san
    volume_group_name = args.volume_group
    volume_names = args.volumes
    # default is 32, also the maximum allowed number of sessions; validate this against your
    # environment's iSCSI/network limits (see README.md) before relying on the default.
    number_of_sessions = (
        min(32, int(args.num_of_sessions)) if args.num_of_sessions is not None else 32
    )

    if None in (resource_group_name, elastic_san_name, volume_group_name, volume_names):
        raise ElasticSanConnectError(
            "Need to provide resource_group_name, elastic_san_name, volume_group_name, "
            "volume_names to connect to the Elastic SAN volume(s)"
        )
    if number_of_sessions < 1:
        raise ElasticSanConnectError(
            "--num-of-sessions must be at least 1 (got {})".format(number_of_sessions)
        )

    check_az_cli_available()

    plans = build_connection_plan(
        args.elastic_san_subscription,
        resource_group_name,
        elastic_san_name,
        volume_group_name,
        volume_names,
        number_of_sessions,
        args.enable_zonal_affinity,
    )

    if args.dry_run:
        print("[dry-run] No mutating commands (sysrc/service/iscsictl) will be run.")
        for line in describe_plan(plans, number_of_sessions):
            print("[dry-run] " + line)
        print(
            "[dry-run] Would write the following managed block to {}:".format(args.config_path)
        )
        print(render_full_managed_block(plans).decode("utf-8"))
        return

    execute_connection_plan(plans, args.config_path, number_of_sessions)


if __name__ == "__main__":
    main()
