"""Standalone Azure Elastic SAN connect script for stock FreeBSD 13+.

This is a separate implementation from the Linux connect script in
"CLI (Linux) Multi-Session Connect Scripts". FreeBSD uses a different iSCSI
initiator stack (iscsid/iscsictl/iscsi.conf, sysrc/service) than Linux
(open-iscsi/iscsiadm, distro package managers), so the two scripts are kept
independent rather than sharing a code path.

Prerequisites (see README.md in this directory for full detail):
    * FreeBSD 13 or later with the native iSCSI initiator
      (iscsi(4)/iscsid(8)/iscsictl(8)) available -- /dev/iscsi must exist.
    * Python 3.
    * Azure CLI ('az') with the 'elastic-san' extension. On FreeBSD, Azure
      CLI is provided by the FreeBSD Ports Collection / community packages
      (e.g. sysutils/py-azure-cli) and is NOT part of Microsoft's
      first-class supported install matrix
      (https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux).
      This script verifies the 'elastic-san' extension is present but cannot
      verify upstream compatibility beyond that -- validate it yourself.
    * Root privileges for any mutating action (writing /etc/iscsi.conf,
      enabling/starting iscsid, adding iSCSI sessions). --dry-run does not
      require root and performs no mutation.

This script intentionally does NOT:
    * call iscsiadm, systemd, or any Linux package manager;
    * call 'iscsictl -R -a' or otherwise remove/tear down sessions;
    * restart the iscsid service or touch sessions it did not create;
    * assemble gmultipath devices (session creation is not multipath device
      assembly -- see README.md).
"""

import argparse
import hashlib
import json
import os
import re
import shutil
import socket
import stat
import subprocess
import sys
import tempfile
import threading
import time

try:
    import fcntl
except ImportError:  # pragma: no cover - tests also run on non-POSIX developer machines
    fcntl = None

try:
    from urllib.request import ProxyHandler, Request, build_opener
    from urllib.error import HTTPError, URLError
except ImportError:  # pragma: no cover - py2 fallback retained for parity with the Linux script
    from urllib2 import HTTPError, ProxyHandler, Request, URLError, build_opener

try:
    string_types = (basestring,)  # noqa: F821 - py2 fallback
except NameError:
    string_types = (str,)


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

IMDS_COMPUTE_URL = "http://169.254.169.254/metadata/instance/compute?api-version=2021-02-01"
IMDS_TIMEOUT_SECONDS = 5
AZ_CLI_TIMEOUT_SECONDS = 30
SHORT_COMMAND_TIMEOUT_SECONDS = 15
ISCSICTL_COMMAND_TIMEOUT_SECONDS = 15
SESSION_READY_TIMEOUT_SECONDS = 30
SESSION_POLL_INTERVAL_SECONDS = 1

MAX_IQN_UTF8_BYTES = 223
PHYSICAL_ZONE_PATTERN = re.compile(r"^[a-z0-9.-]+$")
SUBSCRIPTION_ID_PATTERN = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
)

DEFAULT_ISCSI_CONF_PATH = "/etc/iscsi.conf"
CONFIG_LOCK_FILENAME = ".azure-elastic-san.lock"
ISCSI_DEVICE_NODE = "/dev/iscsi"
REQUIRED_FREEBSD_TOOLS = ("iscsictl", "service", "sysrc")

# These markers are intentionally origin-neutral (no "generated by <this script>" text): both
# this standalone script and the Azure portal's generated FreeBSD connect script write to the
# same /etc/iscsi.conf and must recognize/update each other's managed block rather than treating
# it as a stray, hand-edited marker. Keep this pair byte-for-byte identical to MANAGED_BLOCK_BEGIN
# / MANAGED_BLOCK_END in VolumeHelpers.ts's generateFreeBsdConnectScript.
MANAGED_BLOCK_BEGIN = "# BEGIN AZURE ELASTIC SAN FREEBSD MANAGED BLOCK -- DO NOT EDIT"
MANAGED_BLOCK_END = "# END AZURE ELASTIC SAN FREEBSD MANAGED BLOCK"

# Characters that would break the iscsi.conf(5) grammar or allow one
# configured value to inject a second statement/stanza.
_FORBIDDEN_CONFIG_CHARS = frozenset('"{}#;')
NICKNAME_PATTERN = re.compile(r"^[a-z0-9][a-z0-9_-]{0,127}$")


class ElasticSanConnectError(Exception):
    """Raised for any expected, actionable failure in this script."""


# ---------------------------------------------------------------------------
# Bounded subprocess execution (shared by Azure CLI and FreeBSD tool calls)
# ---------------------------------------------------------------------------

def _decode_output(value):
    return value.decode("utf-8") if isinstance(value, bytes) else value


def _run_subprocess(command, description, timeout):
    """Run *command* (an argv list; never a shell string) with a hard wall-clock
    timeout, returning (returncode, stdout, stderr). Never raises on a non-zero
    exit code -- callers decide whether that is fatal."""
    try:
        process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    except OSError as error:
        raise ElasticSanConnectError("{} failed to start: {}".format(description, error))

    result = []
    communication_errors = []

    def communicate():
        try:
            result.append(process.communicate())
        except (OSError, ValueError) as error:
            communication_errors.append(error)

    communication_thread = threading.Thread(target=communicate)
    communication_thread.daemon = True
    communication_thread.start()
    communication_thread.join(timeout)
    if communication_thread.is_alive():
        process.kill()
        communication_thread.join()
        raise ElasticSanConnectError(
            "{} timed out after {} seconds".format(description, timeout)
        )
    if communication_errors:
        raise ElasticSanConnectError(
            "{} failed while collecting output: {}".format(
                description, communication_errors[0]
            )
        )

    out, err = result[0]
    return process.returncode, _decode_output(out), _decode_output(err).strip()


def _run_command(command, description, timeout=AZ_CLI_TIMEOUT_SECONDS):
    """Run *command* and raise ElasticSanConnectError if it exits non-zero."""
    returncode, out, err = _run_subprocess(command, description, timeout)
    if returncode != 0:
        detail = err if err else "exit code {}".format(returncode)
        raise ElasticSanConnectError("{} failed: {}".format(description, detail))
    return out


def _run_az_command(command, description):
    return _run_command(command, description, AZ_CLI_TIMEOUT_SECONDS)


# ---------------------------------------------------------------------------
# Preflight checks
# ---------------------------------------------------------------------------

def check_az_cli_available():
    """Confirm 'az' is on PATH and the 'elastic-san' extension is installed.

    Azure CLI on FreeBSD is provided by the FreeBSD Ports Collection /
    community packages (e.g. sysutils/py-azure-cli); it is not part of
    Microsoft's first-class supported install matrix. This function verifies
    the elastic-san extension is present, which is the most that can be
    checked programmatically -- broader compatibility must still be
    validated by the operator.
    """
    if shutil.which("az") is None:
        raise ElasticSanConnectError(
            "Azure CLI ('az') was not found on PATH. On FreeBSD, Azure CLI is provided by the "
            "FreeBSD Ports Collection / community packages (e.g. sysutils/py-azure-cli) and is "
            "not part of Microsoft's first-class supported install matrix "
            "(https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux). Install it "
            "and 'az login', then re-run."
        )
    extension_names = _run_az_command(
        ["az", "extension", "list", "--query", "[].name", "--output", "tsv"],
        "Azure CLI extension inventory",
    )
    installed = {name.strip() for name in extension_names.splitlines() if name.strip()}
    if "elastic-san" not in installed:
        raise ElasticSanConnectError(
            "The Azure CLI 'elastic-san' extension is not installed. Because Azure CLI on "
            "FreeBSD is community-provided and not on Microsoft's first-class install matrix, "
            "extension compatibility is not verified upstream and must be checked manually. "
            "Run 'az extension add -n elastic-san', confirm 'az elastic-san volume show --help' "
            "works, and re-run this script."
        )


def check_freebsd_mutation_prerequisites():
    """Preflight required before any mutating action. Not run for --dry-run."""
    if os.geteuid() != 0:
        raise ElasticSanConnectError(
            "This action modifies {} and iSCSI session state, and must be run as root "
            "(re-run under su/doas or another privileged shell). Use --dry-run to preview a "
            "plan without root.".format(DEFAULT_ISCSI_CONF_PATH)
        )
    missing_tools = [tool for tool in REQUIRED_FREEBSD_TOOLS if shutil.which(tool) is None]
    if missing_tools:
        raise ElasticSanConnectError(
            "Required FreeBSD tool(s) not found on PATH: {}. This script targets FreeBSD 13+ "
            "native iSCSI tooling (iscsictl/service/sysrc) only; it does not use iscsiadm, "
            "systemd, or Linux package managers.".format(", ".join(missing_tools))
        )
    if not os.path.exists(ISCSI_DEVICE_NODE):
        raise ElasticSanConnectError(
            "{} was not found, so the FreeBSD iSCSI initiator kernel driver does not appear to "
            "be loaded. Use a GENERIC (or equivalent) kernel with the iscsi_initiator driver, "
            "or load it explicitly ('kldload iscsi', or iscsi_load=\"YES\" in "
            "/boot/loader.conf) before retrying.".format(ISCSI_DEVICE_NODE)
        )


# ---------------------------------------------------------------------------
# IMDS / zonal-affinity helpers
#
# Semantics below (IMDS endpoint/header/no-proxy/timeout, bounded Azure CLI,
# canonical SAN subscription resolution, same-subscription/same-region
# checks, explicit-subscription ARM Locations lookup, mapping validation,
# and the provisional ":az-<physicalZone>" IQN suffix) intentionally mirror
# "CLI (Linux) Multi-Session Connect Scripts/connect_for_documentation.py"
# so operators see identical zonal-affinity behavior on both platforms.
# ---------------------------------------------------------------------------

def get_vm_compute_metadata():
    request = Request(IMDS_COMPUTE_URL, headers={"Metadata": "true"})
    opener = build_opener(ProxyHandler({}))
    try:
        response = opener.open(request, timeout=IMDS_TIMEOUT_SECONDS)
        try:
            payload = _decode_output(response.read())
        finally:
            response.close()
    except HTTPError as error:
        raise ElasticSanConnectError("IMDS request failed with HTTP status {}".format(error.code))
    except URLError as error:
        raise ElasticSanConnectError("IMDS request failed: {}".format(error.reason))
    except socket.timeout:
        raise ElasticSanConnectError(
            "IMDS request timed out after {} seconds".format(IMDS_TIMEOUT_SECONDS)
        )

    try:
        compute = json.loads(payload)
    except ValueError as error:
        raise ElasticSanConnectError("IMDS returned invalid JSON: {}".format(error))
    if not isinstance(compute, dict):
        raise ElasticSanConnectError("IMDS compute metadata must be a JSON object")
    return compute


def _required_metadata_value(compute, field_name):
    value = compute.get(field_name)
    if not isinstance(value, string_types) or not value.strip():
        raise ElasticSanConnectError(
            "IMDS compute metadata is missing a valid '{}' value".format(field_name)
        )
    return value.strip()


def canonicalize_subscription_id(subscription_id, source):
    if not isinstance(subscription_id, string_types):
        raise ElasticSanConnectError("{} subscription ID must be a GUID".format(source))
    canonical_subscription_id = subscription_id.strip().lower()
    if SUBSCRIPTION_ID_PATTERN.match(canonical_subscription_id) is None:
        raise ElasticSanConnectError("{} subscription ID must be a GUID".format(source))
    return canonical_subscription_id


def resolve_elastic_san_subscription_id(elastic_san_subscription):
    command = ["az", "account", "show"]
    if elastic_san_subscription is not None:
        command.extend(["--subscription", elastic_san_subscription])
    command.extend(["--query", "id", "--output", "tsv"])
    subscription_id = _run_az_command(
        command, "Elastic SAN subscription resolution"
    ).strip()
    if not subscription_id:
        raise ElasticSanConnectError("Elastic SAN subscription resolution returned an empty ID")
    return canonicalize_subscription_id(subscription_id, "Elastic SAN")


def get_elastic_san_location(elastic_san_subscription_id, resource_group_name, elastic_san_name):
    command = [
        "az",
        "elastic-san",
        "show",
        "-g",
        resource_group_name,
        "--elastic-san-name",
        elastic_san_name,
        "--subscription",
        elastic_san_subscription_id,
        "--query",
        "location",
        "--output",
        "tsv",
    ]
    location = _run_az_command(command, "Elastic SAN location lookup").strip()
    if not location:
        raise ElasticSanConnectError("Elastic SAN location lookup returned an empty location")
    return location


def get_azure_locations(elastic_san_subscription_id):
    elastic_san_subscription_id = canonicalize_subscription_id(
        elastic_san_subscription_id, "Elastic SAN"
    )
    url = (
        "https://management.azure.com/subscriptions/{}/locations"
        "?api-version=2022-12-01"
    ).format(elastic_san_subscription_id)
    command = ["az", "rest", "--method", "get", "--url", url]
    payload = _run_az_command(command, "Azure location REST query")
    try:
        response = json.loads(payload)
    except ValueError as error:
        raise ElasticSanConnectError(
            "Azure location REST query returned invalid JSON: {}".format(error)
        )
    if not isinstance(response, dict):
        raise ElasticSanConnectError("Azure location REST response must be a JSON object")
    locations = response.get("value")
    if not isinstance(locations, list):
        raise ElasticSanConnectError(
            "Azure location REST response must contain a top-level 'value' array"
        )
    return locations


def map_logical_to_physical_zone(locations, location_name, logical_zone):
    normalized_location = location_name.strip().lower()
    region = None
    for candidate in locations:
        if not isinstance(candidate, dict):
            raise ElasticSanConnectError("Azure location REST response contains a malformed region entry")
        candidate_name = candidate.get("name")
        if (
            isinstance(candidate_name, string_types)
            and candidate_name.strip().lower() == normalized_location
        ):
            region = candidate
            break

    if region is None:
        raise ElasticSanConnectError(
            "Azure location REST response has no region matching Elastic SAN location '{}'".format(
                location_name
            )
        )

    if "availabilityZoneMappings" not in region:
        raise ElasticSanConnectError(
            "Region '{}' is missing availabilityZoneMappings".format(region.get("name"))
        )

    mappings = region["availabilityZoneMappings"]
    if not isinstance(mappings, list) or not mappings:
        raise ElasticSanConnectError(
            "Region '{}' has malformed availabilityZoneMappings".format(region.get("name"))
        )

    normalized_logical_zone = logical_zone.strip()
    zone_map = {}
    for mapping in mappings:
        if not isinstance(mapping, dict):
            raise ElasticSanConnectError("availabilityZoneMappings contains a malformed entry")
        mapped_logical_zone = mapping.get("logicalZone")
        mapped_physical_zone = mapping.get("physicalZone")
        if (
            not isinstance(mapped_logical_zone, string_types)
            or not mapped_logical_zone.strip()
            or not isinstance(mapped_physical_zone, string_types)
            or not mapped_physical_zone.strip()
        ):
            raise ElasticSanConnectError("availabilityZoneMappings contains a malformed entry")
        mapped_logical_zone = mapped_logical_zone.strip()
        mapped_physical_zone = mapped_physical_zone.strip()
        if mapped_logical_zone in zone_map:
            raise ElasticSanConnectError(
                "availabilityZoneMappings contains duplicate logical zone '{}'".format(
                    mapped_logical_zone
                )
            )
        zone_map[mapped_logical_zone] = mapped_physical_zone

    if normalized_logical_zone not in zone_map:
        raise ElasticSanConnectError(
            "Region '{}' has no availability-zone mapping for logical zone '{}'".format(
                region.get("name"), logical_zone
            )
        )
    return zone_map[normalized_logical_zone]


def resolve_physical_zone(elastic_san_subscription, resource_group_name, elastic_san_name):
    compute = get_vm_compute_metadata()
    logical_zone = compute.get("zone")
    if not isinstance(logical_zone, string_types) or not logical_zone.strip():
        raise ElasticSanConnectError(
            "VM is not availability-zone pinned; IMDS compute.zone is empty or missing"
        )
    logical_zone = logical_zone.strip()
    imds_subscription_id = canonicalize_subscription_id(
        _required_metadata_value(compute, "subscriptionId"), "IMDS"
    )
    location_name = _required_metadata_value(compute, "location")

    elastic_san_subscription_id = resolve_elastic_san_subscription_id(elastic_san_subscription)
    if elastic_san_subscription_id != imds_subscription_id:
        raise ElasticSanConnectError(
            "Elastic SAN subscription '{}' does not match VM subscription '{}'".format(
                elastic_san_subscription_id, imds_subscription_id
            )
        )

    elastic_san_location = get_elastic_san_location(
        elastic_san_subscription_id, resource_group_name, elastic_san_name
    )
    if elastic_san_location.strip().lower() != location_name.strip().lower():
        raise ElasticSanConnectError("The VM and Elastic SAN must be in the same region.")

    locations = get_azure_locations(elastic_san_subscription_id)
    return map_logical_to_physical_zone(locations, elastic_san_location, logical_zone)


def decorate_target_iqn(target_iqn, physical_zone):
    normalized_physical_zone = physical_zone.strip().lower()
    if (
        not normalized_physical_zone
        or PHYSICAL_ZONE_PATTERN.match(normalized_physical_zone) is None
    ):
        raise ElasticSanConnectError(
            "Physical zone '{}' contains characters that are unsafe for an IQN suffix".format(
                physical_zone
            )
        )

    # Provisional contract: the Elastic SAN front end must parse and strip this
    # suffix before zonal-affinity routing can be used in production.
    decorated_iqn = "{}:az-{}".format(target_iqn, normalized_physical_zone)
    if len(decorated_iqn.encode("utf-8")) > MAX_IQN_UTF8_BYTES:
        raise ElasticSanConnectError(
            "Decorated target IQN exceeds the {}-byte UTF-8 limit".format(MAX_IQN_UTF8_BYTES)
        )
    return decorated_iqn


def get_volume_storage_target(
    elastic_san_subscription, resource_group_name, elastic_san_name, volume_group_name, volume_name
):
    """Look up a volume's iSCSI target (IQN, portal hostname, portal port)."""
    command = [
        "az",
        "elastic-san",
        "volume",
        "show",
        "-g",
        resource_group_name,
        "-e",
        elastic_san_name,
        "-v",
        volume_group_name,
        "-n",
        volume_name,
        "--query",
        "storageTarget",
        "--output",
        "json",
    ]
    if elastic_san_subscription is not None:
        command.extend(["--subscription", elastic_san_subscription])
    payload = _run_az_command(
        command, "Elastic SAN volume '{}' storage target lookup".format(volume_name)
    )
    try:
        storage_target = json.loads(payload)
    except ValueError as error:
        raise ElasticSanConnectError(
            "Elastic SAN volume '{}' storage target lookup returned invalid JSON: {}".format(
                volume_name, error
            )
        )
    if not isinstance(storage_target, dict):
        raise ElasticSanConnectError(
            "Elastic SAN volume '{}' storage target lookup must return a JSON object".format(
                volume_name
            )
        )
    try:
        target_iqn = storage_target["targetIqn"]
        target_portal_hostname = storage_target["targetPortalHostname"]
        target_portal_port = storage_target["targetPortalPort"]
    except KeyError as error:
        raise ElasticSanConnectError(
            "Elastic SAN volume '{}' storage target response is missing {}".format(
                volume_name, error
            )
        )
    return target_iqn, target_portal_hostname, target_portal_port


# ---------------------------------------------------------------------------
# iscsi.conf value/nickname validation
# ---------------------------------------------------------------------------

def validate_config_scalar(value, field_name):
    """Reject anything that could inject a new statement/stanza into
    iscsi.conf(5) (quotes, braces, comment/statement separators, or control
    characters including newlines) rather than attempting to escape it --
    the format has no documented escape sequence for these characters."""
    if not isinstance(value, string_types) or not value:
        raise ElasticSanConnectError("{} must be a non-empty string".format(field_name))
    if any(ord(character) < 0x20 for character in value):
        raise ElasticSanConnectError(
            "{} contains a control character, which is not permitted in an iscsi.conf "
            "value".format(field_name)
        )
    if any(character in _FORBIDDEN_CONFIG_CHARS for character in value):
        raise ElasticSanConnectError(
            "{} contains one of {} which is not permitted in an iscsi.conf value: {!r}".format(
                field_name, sorted(_FORBIDDEN_CONFIG_CHARS), value
            )
        )
    return value


def sanitize_identity_component(value, field_name):
    if not isinstance(value, string_types) or not value.strip():
        raise ElasticSanConnectError("{} must be a non-empty string".format(field_name))
    lowered = value.strip().lower()
    sanitized = re.sub(r"[^a-z0-9]+", "-", lowered).strip("-")
    if not sanitized:
        raise ElasticSanConnectError(
            "{} '{}' has no [a-z0-9] characters left to build a config nickname from".format(
                field_name, value
            )
        )
    return sanitized


def build_nickname(volume_group_name, volume_name, target_name, session_index):
    """Deterministic, collision-resistant iscsi.conf nickname for one
    (volume group, volume, target IQN, session index) tuple.

    The SHA-256 input is the UTF-8 encoding of a compact JSON array containing
    the raw (unsanitized) values. JSON's string lengths/escaping and array
    boundaries make the identity unambiguous, while matching JSON.stringify
    in the Azure portal implementation.
    """
    sanitized_group = sanitize_identity_component(volume_group_name, "Volume group name")
    sanitized_volume = sanitize_identity_component(volume_name, "Volume name")
    if not isinstance(target_name, string_types) or not target_name:
        raise ElasticSanConnectError("Target IQN must be a non-empty string")
    if session_index != 1:
        raise ElasticSanConnectError(
            "Stock FreeBSD supports exactly one session per Elastic SAN volume in this PoC"
        )

    readable_base = "esan-{}-{}".format(sanitized_group, sanitized_volume)
    identity_json = json.dumps(
        [volume_group_name, volume_name, target_name, session_index],
        ensure_ascii=False,
        separators=(",", ":"),
    )
    identity_hash = hashlib.sha256(identity_json.encode("utf-8")).hexdigest()[:16]
    suffix = "-{}-s1".format(identity_hash)
    readable_prefix = readable_base[: 128 - len(suffix)].rstrip("-")
    nickname = readable_prefix + suffix

    if len(nickname) > 128 or NICKNAME_PATTERN.match(nickname) is None:
        raise ElasticSanConnectError(
            "Generated nickname '{}' is not a safe iscsi.conf identifier (volume group/volume "
            "names may resolve to no usable characters)".format(nickname)
        )
    return nickname


class ManagedConfigEntry(object):
    __slots__ = ("nickname", "target_name", "target_address")

    def __init__(self, nickname, target_name, target_address):
        self.nickname = nickname
        self.target_name = target_name
        self.target_address = target_address


def render_managed_block(entries):
    """Render the full managed block (including BEGIN/END markers) for the
    given ManagedConfigEntry list. TargetName/TargetAddress are pre-validated
    by validate_config_scalar, so quoting them here cannot be broken out of."""
    lines = [MANAGED_BLOCK_BEGIN]
    for entry in entries:
        lines.append("{} {{".format(entry.nickname))
        lines.append('\tTargetName    = "{}"'.format(entry.target_name))
        lines.append('\tTargetAddress = "{}"'.format(entry.target_address))
        lines.append("\tHeaderDigest  = CRC32C")
        lines.append("\tDataDigest    = CRC32C")
        lines.append("\tEnable        = On")
        lines.append("}")
    lines.append(MANAGED_BLOCK_END)
    return ("\n".join(lines) + "\n").encode("utf-8")


_TARGET_NAME_LINE = re.compile(r'^\tTargetName    = "([^"]+)"$')
_TARGET_ADDRESS_LINE = re.compile(r'^\tTargetAddress = "([^"]+)"$')


def parse_managed_block(managed_block_bytes):
    """Strictly parse a block emitted by render_managed_block.

    Unknown, reordered, missing, or duplicate content is rejected so a rerun
    cannot silently discard a stanza that an operator or another generator
    placed between the shared markers.
    """
    try:
        text = managed_block_bytes.decode("utf-8")
    except UnicodeDecodeError as error:
        raise ElasticSanConnectError(
            "The Azure Elastic SAN managed block is not valid UTF-8: {}".format(error)
        )

    lines = text.splitlines()
    if (
        len(lines) < 2
        or lines[0] != MANAGED_BLOCK_BEGIN
        or lines[-1] != MANAGED_BLOCK_END
    ):
        raise ElasticSanConnectError(
            "The Azure Elastic SAN managed block does not have exact BEGIN/END marker lines"
        )

    entries = []
    seen_nicknames = set()
    index = 1
    while index < len(lines) - 1:
        if index + 6 >= len(lines):
            raise ElasticSanConnectError(
                "The Azure Elastic SAN managed block contains incomplete or unknown content"
            )
        nickname_line = lines[index]
        if not nickname_line.endswith(" {"):
            raise ElasticSanConnectError(
                "The Azure Elastic SAN managed block contains unknown content: {!r}".format(
                    nickname_line
                )
            )
        nickname = nickname_line[:-2]
        target_name_match = _TARGET_NAME_LINE.match(lines[index + 1])
        target_address_match = _TARGET_ADDRESS_LINE.match(lines[index + 2])
        expected_tail = [
            "\tHeaderDigest  = CRC32C",
            "\tDataDigest    = CRC32C",
            "\tEnable        = On",
            "}",
        ]
        if (
            NICKNAME_PATTERN.match(nickname) is None
            or target_name_match is None
            or target_address_match is None
            or lines[index + 3 : index + 7] != expected_tail
        ):
            raise ElasticSanConnectError(
                "The Azure Elastic SAN managed block entry starting at {!r} is malformed or "
                "contains unknown content".format(nickname_line)
            )
        if nickname in seen_nicknames:
            raise ElasticSanConnectError(
                "The Azure Elastic SAN managed block contains duplicate nickname '{}'".format(
                    nickname
                )
            )
        seen_nicknames.add(nickname)
        entries.append(
            ManagedConfigEntry(
                nickname,
                validate_config_scalar(target_name_match.group(1), "Managed TargetName"),
                validate_config_scalar(
                    target_address_match.group(1), "Managed TargetAddress"
                ),
            )
        )
        index += 7
    return entries


# ---------------------------------------------------------------------------
# /etc/iscsi.conf atomic update with backup/rollback
# ---------------------------------------------------------------------------

def _split_managed_block(content_bytes):
    """Return (prefix, block, suffix) byte spans around any existing managed
    block in *content_bytes*, preserving everything else byte-for-byte. If no
    managed block markers are present, the whole file is treated as prefix
    (the new block is appended). Raises if exactly one marker is present,
    which indicates hand-edited/corrupted state we should not try to guess
    our way through."""
    begin_bytes = MANAGED_BLOCK_BEGIN.encode("utf-8")
    end_bytes = MANAGED_BLOCK_END.encode("utf-8")
    begin_index = content_bytes.find(begin_bytes)
    end_index = content_bytes.find(end_bytes)

    if begin_index == -1 and end_index == -1:
        return content_bytes, None, b""

    if begin_index == -1 or end_index == -1:
        raise ElasticSanConnectError(
            "{} contains only one of the managed-block BEGIN/END markers. Refusing to modify "
            "it automatically; restore the file from a backup or remove the stray marker line "
            "by hand before retrying.".format(DEFAULT_ISCSI_CONF_PATH)
        )
    if (
        (begin_index > 0 and content_bytes[begin_index - 1 : begin_index] != b"\n")
        or content_bytes[
            begin_index + len(begin_bytes) : begin_index + len(begin_bytes) + 1
        ]
        not in (b"", b"\n")
        or (end_index > 0 and content_bytes[end_index - 1 : end_index] != b"\n")
        or content_bytes[end_index + len(end_bytes) : end_index + len(end_bytes) + 1]
        not in (b"", b"\n")
    ):
        raise ElasticSanConnectError(
            "{} contains a managed-block marker that is not an exact standalone line. "
            "Refusing to modify it automatically.".format(DEFAULT_ISCSI_CONF_PATH)
        )
    if end_index < begin_index:
        raise ElasticSanConnectError(
            "{} has a managed-block END marker before its BEGIN marker. Refusing to modify it "
            "automatically.".format(DEFAULT_ISCSI_CONF_PATH)
        )

    end_line_terminator = content_bytes.find(b"\n", end_index)
    end_of_end_line = end_line_terminator + 1 if end_line_terminator != -1 else len(content_bytes)
    prefix = content_bytes[:begin_index]
    block = content_bytes[begin_index:end_of_end_line]
    suffix = content_bytes[end_of_end_line:]

    # Guard against a second, stray marker pair further down the file (e.g.
    # from a manually concatenated/restored backup). We already refuse to
    # guess our way through a single stray marker above; a duplicate pair
    # deserves the same treatment rather than being silently preserved in
    # 'suffix' forever.
    if begin_bytes in suffix or end_bytes in suffix:
        raise ElasticSanConnectError(
            "{} contains more than one managed-block marker pair. Refusing to modify it "
            "automatically; remove the duplicate BEGIN/END markers by hand before "
            "retrying.".format(DEFAULT_ISCSI_CONF_PATH)
        )

    return prefix, block, suffix


def compute_new_config_content(existing_content_bytes, managed_block_bytes):
    prefix, existing_block, suffix = _split_managed_block(existing_content_bytes)
    existing_entries = (
        parse_managed_block(existing_block) if existing_block is not None else []
    )
    selected_entries = parse_managed_block(managed_block_bytes)
    if not selected_entries:
        raise ElasticSanConnectError(
            "Refusing to write an empty Azure Elastic SAN connection plan"
        )

    merged_by_nickname = {entry.nickname: entry for entry in existing_entries}
    for entry in selected_entries:
        existing_entry = merged_by_nickname.get(entry.nickname)
        if existing_entry is not None and (
            existing_entry.target_name != entry.target_name
            or existing_entry.target_address != entry.target_address
        ):
            raise ElasticSanConnectError(
                "Generated nickname '{}' conflicts with an existing managed entry: "
                "existing target/address is '{}'/'{}', selected target/address is "
                "'{}'/'{}'. Refusing to overwrite it.".format(
                    entry.nickname,
                    existing_entry.target_name,
                    existing_entry.target_address,
                    entry.target_name,
                    entry.target_address,
                )
            )
        merged_by_nickname[entry.nickname] = entry
    merged_block = render_managed_block(
        [merged_by_nickname[nickname] for nickname in sorted(merged_by_nickname)]
    )
    if prefix and not prefix.endswith(b"\n"):
        prefix += b"\n"
    return prefix + merged_block + suffix


def read_config_file(path):
    """Return (content_bytes, existed, stat_result_or_None)."""
    if not os.path.exists(path):
        return b"", False, None
    with open(path, "rb") as handle:
        content = handle.read()
    return content, True, os.stat(path)


def get_config_lock_path(config_path):
    """Return the stable lock inode used to serialize config transactions."""
    return os.path.join(
        os.path.dirname(os.path.abspath(config_path)), CONFIG_LOCK_FILENAME
    )


def acquire_config_transaction_lock(config_path):
    """Securely open and exclusively lock the config's separate lock file.

    The lock cannot live on iscsi.conf itself because atomic replacement changes
    that inode. The returned (path, fd) pair remains owned by the caller until
    release_config_transaction_lock() is called.
    """
    if fcntl is None:
        raise ElasticSanConnectError(
            "fcntl.flock is unavailable; config transactions require a POSIX/FreeBSD host"
        )

    lock_path = get_config_lock_path(config_path)
    flags = os.O_CREAT | os.O_RDWR
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW

    try:
        lock_fd = os.open(lock_path, flags, 0o600)
    except OSError as error:
        raise ElasticSanConnectError(
            "Failed to securely open config transaction lock '{}': {}".format(
                lock_path, error
            )
        )

    try:
        opened_stat = os.fstat(lock_fd)
        path_stat = os.lstat(lock_path)
        if (
            not stat.S_ISREG(opened_stat.st_mode)
            or stat.S_ISLNK(path_stat.st_mode)
            or opened_stat.st_dev != path_stat.st_dev
            or opened_stat.st_ino != path_stat.st_ino
        ):
            raise ElasticSanConnectError(
                "Config transaction lock '{}' must be a non-symlink regular file".format(
                    lock_path
                )
            )
        fcntl.flock(lock_fd, fcntl.LOCK_EX)
    except ElasticSanConnectError:
        os.close(lock_fd)
        raise
    except OSError as error:
        os.close(lock_fd)
        raise ElasticSanConnectError(
            "Failed to acquire config transaction lock '{}': {}".format(lock_path, error)
        )

    return lock_path, lock_fd


def release_config_transaction_lock(lock_fd):
    """Release and close a lock handle returned by acquire_config_transaction_lock."""
    try:
        fcntl.flock(lock_fd, fcntl.LOCK_UN)
    finally:
        os.close(lock_fd)


def backup_config(path, existing_content_bytes, existed):
    """Write a backup of the current config content before mutating it.
    Returns the backup path (or None if the file did not exist yet, in which
    case there is nothing to back up)."""
    if not existed:
        return None
    backup_path = "{}.bak.pre-esan-connect.{}".format(path, os.getpid())
    directory = os.path.dirname(path) or "."
    fd, temp_path = tempfile.mkstemp(prefix=".iscsi.conf.bak.", dir=directory)
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(existing_content_bytes)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temp_path, backup_path)
    except BaseException:
        if os.path.exists(temp_path):
            os.remove(temp_path)
        raise
    return backup_path


def write_config_atomically(path, new_content_bytes, original_stat):
    """Write *new_content_bytes* to *path* atomically via a temp file in the
    same directory + os.replace, preserving the original file's permissions
    and ownership where possible."""
    directory = os.path.dirname(path) or "."
    fd, temp_path = tempfile.mkstemp(prefix=".iscsi.conf.new.", dir=directory)
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(new_content_bytes)
            handle.flush()
            os.fsync(handle.fileno())
        if original_stat is not None:
            os.chmod(temp_path, original_stat.st_mode & 0o7777)
            # Ownership preservation only applies on platforms that expose
            # os.chown (i.e. POSIX/FreeBSD, the only supported target for
            # this script) -- "where possible" per the design requirements.
            if hasattr(os, "chown"):
                try:
                    os.chown(temp_path, original_stat.st_uid, original_stat.st_gid)
                except OSError as error:
                    raise ElasticSanConnectError(
                        "Failed to preserve ownership of {} on the replacement file: {}".format(
                            path, error
                        )
                    )
        else:
            os.chmod(temp_path, 0o644)
        os.replace(temp_path, path)
    except BaseException:
        if os.path.exists(temp_path):
            os.remove(temp_path)
        raise


def restore_config_from_backup(path, backup_path, existed, original_stat):
    """Roll back a mutation: restore the pre-mutation content and permissions
    (or remove the file entirely if it did not exist before this run created
    it). *original_stat* must be the stat() of the file captured before it
    was mutated -- the backup file itself is deliberately created with
    restrictive permissions regardless of the original file's mode, since
    unrelated stanzas preserved outside the managed block may contain CHAP
    secrets."""
    if not existed:
        if os.path.exists(path):
            os.remove(path)
        return
    with open(backup_path, "rb") as handle:
        backup_content = handle.read()
    write_config_atomically(path, backup_content, original_stat)


# ---------------------------------------------------------------------------
# iscsid service management
# ---------------------------------------------------------------------------

def ensure_iscsid_enabled_and_running():
    returncode, current, _ = _run_subprocess(
        ["sysrc", "-n", "iscsid_enable"], "sysrc iscsid_enable query", SHORT_COMMAND_TIMEOUT_SECONDS
    )
    if returncode != 0:
        current = ""
    if current.strip().upper() != "YES":
        _run_command(
            ["sysrc", "iscsid_enable=YES"], "sysrc iscsid_enable=YES", SHORT_COMMAND_TIMEOUT_SECONDS
        )
    returncode, _, _ = _run_subprocess(
        ["service", "iscsid", "onestatus"], "service iscsid onestatus", SHORT_COMMAND_TIMEOUT_SECONDS
    )
    if returncode != 0:
        _run_command(
            ["service", "iscsid", "start"], "service iscsid start", SHORT_COMMAND_TIMEOUT_SECONDS
        )


# ---------------------------------------------------------------------------
# iscsictl session inspection/management
# ---------------------------------------------------------------------------

def list_iscsi_sessions():
    """Parse 'iscsictl -L -v' into a list of per-session field dicts (keys
    such as 'Target name', 'Target portal', 'Session state'). The nickname
    used to add a session is not part of the kernel's session state and is
    therefore not recoverable from this listing. Sessions are correlated by
    Target name only because an iSCSI TargetAddress redirect can legitimately
    change Target portal after login."""
    output = _run_command(
        ["iscsictl", "-L", "-v"], "iscsictl session listing", AZ_CLI_TIMEOUT_SECONDS
    )
    return _parse_iscsictl_verbose_sessions(output)


def _parse_iscsictl_verbose_sessions(output):
    sessions = []
    fields = {}

    def append_session():
        if not fields:
            return
        required_fields = ("Target name", "Target portal", "Session state")
        missing_fields = [field for field in required_fields if field not in fields]
        if missing_fields:
            raise ElasticSanConnectError(
                "Could not safely parse 'iscsictl -L -v': a session block is missing {}".format(
                    ", ".join(missing_fields)
                )
            )
        sessions.append(dict(fields))

    for line in output.splitlines() + [""]:
        if not line.strip():
            append_session()
            fields = {}
            continue
        if ":" not in line:
            continue
        label, _, value = line.partition(":")
        label = label.strip()
        if label == "Session ID" and fields:
            append_session()
            fields = {}
        fields[label] = value.strip()
    return sessions


def sessions_for_target(sessions, target_name):
    return [
        session for session in sessions if session.get("Target name") == target_name
    ]


def session_is_connected(session):
    return (
        session.get("Session state", "").strip().lower() == "connected"
        and session.get("Enable", "Yes").strip().lower() not in ("no", "off", "disabled")
    )


def add_iscsi_session(nickname, config_path):
    command = [
        "iscsictl",
        "-A",
        "-n",
        nickname,
        "-c",
        config_path,
    ]
    _run_command(
        command, "iscsictl add session '{}'".format(nickname), ISCSICTL_COMMAND_TIMEOUT_SECONDS
    )


def wait_for_connected_session(
    target_name,
    timeout=SESSION_READY_TIMEOUT_SECONDS,
    poll_interval=SESSION_POLL_INTERVAL_SECONDS,
    monotonic=None,
    sleep=None,
):
    """Poll only *target_name* until a connected session is visible."""
    monotonic = time.monotonic if monotonic is None else monotonic
    sleep = time.sleep if sleep is None else sleep
    deadline = monotonic() + timeout
    while True:
        matching_sessions = sessions_for_target(list_iscsi_sessions(), target_name)
        if any(session_is_connected(session) for session in matching_sessions):
            return
        now = monotonic()
        if now >= deadline:
            raise ElasticSanConnectError(
                "Timed out after {} seconds waiting for target '{}' to become Connected. "
                "The iscsictl add request was already submitted and may still create or leave "
                "a live session; inspect 'iscsictl -L -v' before retrying.".format(
                    timeout, target_name
                )
            )
        sleep(min(poll_interval, deadline - now))


# ---------------------------------------------------------------------------
# Connection planning (shared by --dry-run and the real execution path)
# ---------------------------------------------------------------------------

class VolumeConnectionPlan(object):
    __slots__ = ("volume_name", "target_name", "target_address", "nicknames")

    def __init__(self, volume_name, target_name, target_address, nicknames):
        self.volume_name = volume_name
        self.target_name = target_name
        self.target_address = target_address
        self.nicknames = nicknames


def build_connection_plan(
    elastic_san_subscription,
    resource_group_name,
    elastic_san_name,
    volume_group_name,
    volume_names,
    number_of_sessions,
    enable_zonal_affinity=False,
):
    """Resolve targets and compute the deterministic nickname set for every
    volume. This performs only read-only discovery (IMDS, Azure CLI) and pure
    computation -- no filesystem or iscsictl calls -- so it is identical for
    --dry-run and the real execution path."""
    if not volume_names:
        raise ElasticSanConnectError(
            "At least one volume must be selected; refusing to build an empty connection plan"
        )
    if number_of_sessions != 1:
        raise ElasticSanConnectError(
            "Stock FreeBSD rejects duplicate target-name/portal sessions, so this PoC supports "
            "exactly one session per volume. NetApp-specific multi-session behavior requires "
            "separate validation."
        )

    physical_zone = (
        resolve_physical_zone(elastic_san_subscription, resource_group_name, elastic_san_name)
        if enable_zonal_affinity
        else None
    )

    plans = []
    nickname_owners = {}
    for volume_name in volume_names:
        target_iqn, target_hostname, target_port = get_volume_storage_target(
            elastic_san_subscription,
            resource_group_name,
            elastic_san_name,
            volume_group_name,
            volume_name,
        )
        if enable_zonal_affinity:
            target_iqn = decorate_target_iqn(target_iqn, physical_zone)

        target_name = validate_config_scalar(target_iqn, "Target IQN for '{}'".format(volume_name))
        target_address = validate_config_scalar(
            "{}:{}".format(target_hostname, target_port),
            "Target address for '{}'".format(volume_name),
        )
        nicknames = [
            build_nickname(volume_group_name, volume_name, target_name, session_index)
            for session_index in range(1, number_of_sessions + 1)
        ]
        for nickname in nicknames:
            previous_volume = nickname_owners.get(nickname)
            if previous_volume is not None:
                raise ElasticSanConnectError(
                    "Connection plan generated duplicate nickname '{}' for volumes '{}' and "
                    "'{}'; refusing to continue".format(
                        nickname, previous_volume, volume_name
                    )
                )
            nickname_owners[nickname] = volume_name
        plans.append(VolumeConnectionPlan(volume_name, target_name, target_address, nicknames))
    return plans


def render_full_managed_block(plans):
    entries = []
    seen_nicknames = set()
    for plan in plans:
        for nickname in plan.nicknames:
            if nickname in seen_nicknames:
                raise ElasticSanConnectError(
                    "Connection plan contains duplicate nickname '{}'; refusing to render it".format(
                        nickname
                    )
                )
            seen_nicknames.add(nickname)
            entries.append(
                ManagedConfigEntry(nickname, plan.target_name, plan.target_address)
            )
    if not entries:
        raise ElasticSanConnectError(
            "Refusing to render an empty Azure Elastic SAN connection plan"
        )
    return render_managed_block(entries)


def describe_plan(plans, number_of_sessions):
    lines = []
    for plan in plans:
        lines.append(
            "{} -> target {} at {} ({} session(s), nicknames: {})".format(
                plan.volume_name,
                plan.target_name,
                plan.target_address,
                number_of_sessions,
                ", ".join(plan.nicknames),
            )
        )
    return lines


# ---------------------------------------------------------------------------
# Execution path (mutating)
# ---------------------------------------------------------------------------

def add_sessions_for_volume(plan, config_path, desired_sessions):
    if desired_sessions != 1 or len(plan.nicknames) != 1:
        raise ElasticSanConnectError(
            "Stock FreeBSD supports exactly one session per volume in this PoC"
        )
    existing_sessions = list_iscsi_sessions()
    matching_sessions = sessions_for_target(existing_sessions, plan.target_name)
    if len(matching_sessions) > 1:
        raise ElasticSanConnectError(
            "{}: found {} sessions for target '{}', but stock FreeBSD supports exactly one "
            "in this PoC. This script will not remove sessions; inspect 'iscsictl -L -v' and "
            "reconcile the duplicates manually.".format(
                plan.volume_name, len(matching_sessions), plan.target_name
            )
        )
    unhealthy_sessions = [
        session for session in matching_sessions if not session_is_connected(session)
    ]
    if unhealthy_sessions:
        states = sorted(
            set(
                "{}{}".format(
                    session.get("Session state", "<missing>"),
                    " (disabled)"
                    if session.get("Enable", "Yes").strip().lower()
                    in ("no", "off", "disabled")
                    else "",
                )
                for session in unhealthy_sessions
            )
        )
        raise ElasticSanConnectError(
            "{}: found an existing non-connected session for target '{}' (state: {}). "
            "The script will not add a duplicate or remove the stale session. Inspect "
            "'iscsictl -L -v', recover or remove that specific session manually, and retry.".format(
                plan.volume_name, plan.target_name, ", ".join(states)
            )
        )

    if matching_sessions:
        print(
            "{} [{}]: Skipped -- a Connected session is already established".format(
                plan.volume_name, plan.target_name
            )
        )
        return

    add_iscsi_session(plan.nicknames[0], config_path)
    wait_for_connected_session(plan.target_name)
    print(
        "{} [{}]: Connected".format(plan.volume_name, plan.target_name)
    )


def execute_connection_plan(plans, config_path, number_of_sessions):
    if not plans:
        raise ElasticSanConnectError(
            "Refusing to execute an empty Azure Elastic SAN connection plan"
        )
    if number_of_sessions != 1 or any(len(plan.nicknames) != 1 for plan in plans):
        raise ElasticSanConnectError(
            "Stock FreeBSD supports exactly one session per volume in this PoC"
        )
    check_freebsd_mutation_prerequisites()
    _, lock_fd = acquire_config_transaction_lock(config_path)
    try:
        existing_content_bytes, existed, original_stat = read_config_file(config_path)
        new_managed_block = render_full_managed_block(plans)
        new_content = compute_new_config_content(existing_content_bytes, new_managed_block)

        ensure_iscsid_enabled_and_running()
        backup_path = backup_config(config_path, existing_content_bytes, existed)
        write_config_atomically(config_path, new_content, original_stat)

        try:
            for plan in plans:
                add_sessions_for_volume(plan, config_path, number_of_sessions)
        except (ElasticSanConnectError, OSError) as error:
            restore_config_from_backup(config_path, backup_path, existed, original_stat)
            raise ElasticSanConnectError(
                "Failed while establishing iSCSI sessions; restored {} to its pre-run state. "
                "This rollback only restores the config file: an iscsictl add request may already "
                "have created or may still create a live session, and this script never removes "
                "sessions. Inspect 'iscsictl -L -v' before retrying. Original error: {}".format(
                    config_path, error
                )
            )
    finally:
        release_config_transaction_lock(lock_fd)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def create_argument_parser():
    parser = argparse.ArgumentParser(
        description=(
            "Connect one or more Azure Elastic SAN volumes with one iSCSI session each on "
            "stock FreeBSD 13+, using the native iscsid/iscsictl initiator."
        )
    )
    parser.add_argument(
        "--elastic-san-subscription",
        "--subscription",
        dest="elastic_san_subscription",
        help=(
            "Elastic SAN resource subscription name or ID. --subscription is retained as a "
            "compatibility alias."
        ),
    )
    parser.add_argument("-g", "--resource-group", dest="resource_group")
    parser.add_argument("-e", "--elastic-san", dest="elastic_san")
    parser.add_argument("-v", "--volume-group", dest="volume_group")
    parser.add_argument("-n", "--volumes", dest="volumes", nargs="+")
    parser.add_argument(
        "-s",
        "--num-of-sessions",
        dest="num_of_sessions",
        default="1",
        help="Sessions per volume; stock FreeBSD supports exactly 1 in this PoC (default: 1)",
    )
    parser.add_argument(
        "--enable-zonal-affinity",
        action="store_true",
        help=(
            "Opt in to provisional logical-to-physical availability-zone routing. Requires "
            "Elastic SAN front-end support for parsing the IQN suffix."
        ),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help=(
            "Perform all read-only discovery/mapping/config planning and print the plan, "
            "without running sysrc, service, or iscsictl, and without writing "
            + DEFAULT_ISCSI_CONF_PATH
            + ". Does not require root. Existing session counts are not inspected in this mode "
            "(inspecting them requires root); the plan assumes zero pre-existing sessions."
        ),
    )
    parser.add_argument(
        "--config-path",
        dest="config_path",
        default=DEFAULT_ISCSI_CONF_PATH,
        help=argparse.SUPPRESS,  # override for tests only; not part of the public CLI contract
    )
    return parser


def main(argv=None):
    parser = create_argument_parser()
    args = parser.parse_args(sys.argv[1:] if argv is None else argv)

    resource_group_name = args.resource_group
    elastic_san_name = args.elastic_san
    volume_group_name = args.volume_group
    volume_names = args.volumes
    if None in (resource_group_name, elastic_san_name, volume_group_name, volume_names):
        raise ElasticSanConnectError(
            "Need to provide resource_group_name, elastic_san_name, volume_group_name, "
            "volume_names to connect to the Elastic SAN volume(s)"
        )
    try:
        number_of_sessions = int(args.num_of_sessions)
    except (TypeError, ValueError):
        raise ElasticSanConnectError(
            "--num-of-sessions must be exactly 1 for stock FreeBSD (got {!r})".format(
                args.num_of_sessions
            )
        )
    if number_of_sessions != 1:
        raise ElasticSanConnectError(
            "Stock FreeBSD rejects duplicate target-name/portal sessions, so "
            "--num-of-sessions must be exactly 1 (got {}). NetApp-specific multi-session "
            "behavior requires separate validation.".format(number_of_sessions)
        )

    check_az_cli_available()

    plans = build_connection_plan(
        args.elastic_san_subscription,
        resource_group_name,
        elastic_san_name,
        volume_group_name,
        volume_names,
        number_of_sessions,
        args.enable_zonal_affinity,
    )

    if args.dry_run:
        print("[dry-run] No mutating commands (sysrc/service/iscsictl) will be run.")
        for line in describe_plan(plans, number_of_sessions):
            print("[dry-run] " + line)
        print(
            "[dry-run] Would merge the following selected entries into the managed block in "
            "{} (existing config is not read in dry-run mode):".format(args.config_path)
        )
        print(render_full_managed_block(plans).decode("utf-8"))
        return

    execute_connection_plan(plans, args.config_path, number_of_sessions)


if __name__ == "__main__":
    main()
